// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://polzdhlstwdvzmyxflrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvbHpkaGxzdHdkdnpteXhmbHJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5NjQzNDcsImV4cCI6MjA3ODU0MDM0N30.-N1EtLTgpMPsYg5vsq6x806Q6vn_bgc2nliL-a_PleA";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
